export const state = {
  isPt: document.documentElement.lang.startsWith("pt"),
  tlActiveSeason: "2025/26",
  tlActiveWindow: "All",
  healthBarIdx: null,
  storyIndex: 0,
  activeEventFilter: "all",
  DATASET: null,
  annual: null,
  TRANSFER_LEDGER: null,
  renderedCharts: new Set(),
  VALID_TABS: [
    "overview",
    "revenue",
    "healthcheck",
    "debt",
    "bonds",
    "squad",
    "cash",
    "compare",
    "events",
    "data",
    "news",
  ],
  TAB_CHARTS: {},
  COLORS: {},
  baseOpts: {},
};
